require "json"
require "prism"

require_relative "crap4ruby/version"
require_relative "crap4ruby/failure"
require_relative "crap4ruby/method_info"
require_relative "crap4ruby/method_extractor"
require_relative "crap4ruby/attribution"
require_relative "crap4ruby/row"
require_relative "crap4ruby/coverage_report"
require_relative "crap4ruby/project"
require_relative "crap4ruby/test_runner"
require_relative "crap4ruby/report"
require_relative "crap4ruby/cli"
